SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;;D:\Microsoft VS Code\bin
SET CPU_TYPE=MIMXRT1052CVL5B
SET CPU_VENDOR=NXP
SET UV2_TARGET=nor_txt_ram
SET CPU_CLOCK=0x00B71B00
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\system_mimxrt1052.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmAsm" --Via ".\nor_txt_ram\objects\startup_mimxrt1052._ia"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_clock.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_gpio.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_lpuart.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_common.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_snvs_hp.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_assert.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_notifier.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_shell.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_sbrk.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_debug_console.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_str.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_log.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_io.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\board.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\clock_config.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\pin_mux.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\main.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\bsp_snvs_hp_rtc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fire_imxrt1052_sdram_ini_dcd.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fire_imxrt1052_spiflash_config.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\nor_txt_ram\objects\fsl_flexspi_nor_boot.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via ".\nor_txt_ram\Objects\YH-RT1052.lnp"
